package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"go_server/graph/dataloader"
	"go_server/graph/model"
	"go_server/service"
)

// Photos is the resolver for the photos field.
func (r *albumResolver) Photos(ctx context.Context, obj *model.Album) ([]*model.Photo, error) {
	return dataloader.LoadAlbumPhotos(ctx, obj.ID)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	user_svc := service.User{HC: r.HttpClient}
	return user_svc.GetAll()
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id int) (*model.User, error) {
	user_svc := service.User{HC: r.HttpClient}
	return user_svc.Get(id)
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	post_svc := service.Post{HC: r.HttpClient}
	return post_svc.GetAll()
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int) (*model.Post, error) {
	post_svc := service.Post{HC: r.HttpClient}
	return post_svc.Get(id)
}

// Albums is the resolver for the albums field.
func (r *queryResolver) Albums(ctx context.Context) ([]*model.Album, error) {
	album_svc := service.Album{HC: r.HttpClient}
	return album_svc.GetAll()
}

// Album is the resolver for the album field.
func (r *queryResolver) Album(ctx context.Context, id int) (*model.Album, error) {
	album_svc := service.Album{HC: r.HttpClient}
	return album_svc.Get(id)
}

// Photos is the resolver for the photos field.
func (r *queryResolver) Photos(ctx context.Context) ([]*model.Photo, error) {
	photo_svc := service.Photo{HC: r.HttpClient}
	return photo_svc.GetAll()
}

// Photo is the resolver for the photo field.
func (r *queryResolver) Photo(ctx context.Context, id int) (*model.Photo, error) {
	photo_svc := service.Photo{HC: r.HttpClient}
	return photo_svc.Get(id)
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *model.User) ([]*model.Post, error) {
	return dataloader.LoadUserPosts(ctx, obj.ID)
}

// Albums is the resolver for the albums field.
func (r *userResolver) Albums(ctx context.Context, obj *model.User) ([]*model.Album, error) {
	return dataloader.LoadUserAlbums(ctx, obj.ID)
}

// Album returns AlbumResolver implementation.
func (r *Resolver) Album() AlbumResolver { return &albumResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type albumResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
