package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"go_server/graph/model"
	"go_server/service"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	todo_svc := service.Todo{DB: r.DB}
	return todo_svc.Create(input)
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, input model.UpdateTodo) (*model.Todo, error) {
	todo_svc := service.Todo{DB: r.DB}
	return todo_svc.Update(input)
}

// RemoveTodoParent is the resolver for the removeTodoParent field.
func (r *mutationResolver) RemoveTodoParent(ctx context.Context, input int) (*model.Todo, error) {
	todo_svc := service.Todo{DB: r.DB}
	return todo_svc.RemoveParent(input)
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, input int) (string, error) {
	todo_svc := service.Todo{DB: r.DB}
	return todo_svc.Delete(input)
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	todo_svc := service.Todo{DB: r.DB}
	return todo_svc.GetAll()
}

// Parent is the resolver for the parent field.
func (r *todoResolver) Parent(ctx context.Context, obj *model.Todo) (*model.Todo, error) {
	if obj.ParentID == nil {
		return nil, nil
	}
	todo_svc := service.Todo{DB: r.DB}
	return todo_svc.Get(*obj.ParentID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
